name: release-chart
on:
  push:
    tags: 'chart-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: chart
          charts_url: https://neticdk.github.io/helm-operator
          owner: neticdk
          repository: helm-operator
          branch: gh-pages
